[build]
builder = "DOCKERFILE"
dockerfilePath = "Backend/Dockerfile"

[deploy]
startCommand = "uvicorn routes:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
